---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: explore-webhook
  labels:
    app: explore-webhook
webhooks:
  - name: explore-webhook.default.svc.cluster.local
    clientConfig:
      url: "https://2c17bca6.ngrok.io/decorate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    namespaceSelector:
      matchLabels:
        explore: enabled